name: Docker Build and Push

on:
  push:
    branches: [ "main" ] # 只在 main 分支被推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu runner

    steps:
      - name: Checkout repository # 步骤1：签出代码
        uses: actions/checkout@v4

      - name: Set up QEMU # 步骤2：设置 QEMU（用于多平台构建）
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # 步骤3：设置 Docker Buildx（更强大的构建器）
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub # 步骤4：登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 使用 GitHub Secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # 使用 GitHub Secret (访问令牌)

      - name: Build and push Docker image # 步骤5：构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: . # Docker build 的上下文路径 (项目根目录)
          file: ./Dockerfile # Dockerfile 的路径
          platforms: linux/amd64,linux/arm64 # 构建的目标平台 (可选, 推荐)
          push: true # 确认执行推送操作
          tags: | # 为镜像打标签
            krisxia/miko-news:latest
            krisxia/miko-news:${{ github.sha }}
